### PR TITLE
deps: update a4 to v2204.1

### PR DESCRIPTION
**Pull request by Rineee**

### CODE REVIEW

**Comment by fuzzylogic2000** [comment]
Did install and looks fine, but the annotations in the idea list are not there?! Or was it sth. else we wanted to fix?

**Comment by fuzzylogic2000** [comment]
> Did install and looks fine, but the annotations in the idea list are not there?! Or was it sth. else we wanted to fix?

Right, there are there for other sortings, only not for daily random. :grimacing:

**Comment by Rineee** [comment]
> > Did install and looks fine, but the annotations in the idea list are not there?! Or was it sth. else we wanted to fix?
> 
> Right, there are there for other sortings, only not for daily random. grimacing

No, but that was the fix, that they should now also be there for daily random and the are for me ?? I will check again!

**Comment by Rineee** [comment]
image

Not there for you?

**Comment by fuzzylogic2000** [comment]
> image
> 
> Not there for you?

Yes, it's there after `make clean` before installing. Wouldn't have thought I would need that. But yeah!

**Pull request merged**
